export default interface CellMetaDataShape {
  selected: any,
  copied: any,
  dragged: any,
  enableCellSelect?: boolean,
  isScrollingVerticallyWithKeyboard?: boolean,
  isScrollingHorizontallyWithKeyboard?: boolean,
  rowKey?: any,
  onCellClick(obj?: {}, e?: any): void,
  onCellDoubleClick(obj?: {}, e?: any): void,
  onCommit(obj?: any): void,
  onCommitCancel(): void,
  handleDragEnterRow(idx: any): void,
  handleTerminateDrag(): void,
  onRowExpandToggle(obj: any): any,
  onCellContextMenu(obj?: any): any,
  onCellExpand(obj?: any): any,
  onDeleteSubRow(obj?: any): any,
  onDragHandleDoubleClick(obj?: any): any,
  getDataGridDOMNode(): any,
  onColumnEvent(obj?: any, e?: any): any,
};
