# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

jobs:
- job: time_modified_check

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        #!/bin/bash
      
        TIMEMODIFIED=$(npm view engage-ui time.modified)
        EPOCHTIMEMODIFIED=$(date -d "$TIMEMODIFIED" +%s)
        EPOCHYESTERDAY=$(date -d "yesterday" +%s)
      
        if [ "$EPOCHTIMEMODIFIED" -gt "$EPOCHYESTERDAY" ]; then
          echo "Engage-UI has been modified. Triggering build Pipelines"
          exit
        else
          echo "Engage-UI at latest version no need to trigger Build Pipelines"
        fi

- job: run_dependant_builds
  dependsOn: time_modified_check
  condition: failed()
  steps:
  - task: TriggerPipeline@1
    inputs:
      serviceConnection: 'Trigger Builds'
      project: '2072a0a1-0afd-42e6-895f-941998c2ccce'
      Pipeline: 'Build'
      buildDefinition: 'emgage.emgage-frontend'
      Branch: 'develop'